gpu: drm: display: indent fix in comment
The comments explaining the function "drm_dp_mst_atom_check_mgr()" had
uneven indentation which made "make htmldocs" complain:

	Documentation/gpu/drm-kms-helpers:296:
	./drivers/gpu/drm/display/drm_dp_mst_topology.c:5496:
	ERROR: Unexpected indentation.

	Documentation/gpu/drm-kms-helpers:296:
	./drivers/gpu/drm/display/drm_dp_mst_topology.c:5500:
	WARNING: Block quote ends without a blank line; unexpected unindent.

Fix this by getting the indent right.

Signed-off-by: Kousik Sanagavarapu <five231003@gmail.com>